# Generated by Django 6.0.2 on 2026-03-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metodo_de_pago', models.CharField(max_length=50)),
                ('valor_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_kilo_miel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
            options={
                'db_table': 'operaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='main.producto')),
                ('operacion', models.ForeignKey(db_column='id_operacion', on_delete=django.db.models.deletion.CASCADE, to='main.operacion')),
            ],
            options={
                'db_table': 'detalle_operaciones',
                'constraints': [models.UniqueConstraint(fields=('operacion', 'producto'), name='unique_operacion_producto')],
            },
        ),
    ]
