# Generated by Django 6.0.2 on 2026-03-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_producto_activo_operacion_detalleoperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
