# Generated by Django 6.0.2 on 2026-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pagos_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Miel', 'Miel'), ('Alimento', 'Alimento'), ('Cera', 'Cera'), ('Madera', 'Madera'), ('Estampa', 'Estampa'), ('Insumos', 'Insumos'), ('Medicamentos', 'Medicamentos'), ('Otros', 'Otros')], max_length=50, null=True),
        ),
    ]
